# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Period Box - against menstruation poverty
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a box against menstruation poverty.  
  Help the community by setting up your own Period Box and filling it 
  with some spare products. Feel free to print out and attach our 
  flyer to spread the word. Just take your Period Box to the nearest 
  frequently visited public restroom or other space you can imagine fits 
  the purpose (ask the toilet owner first). 
baseurl: "" # the subpath of your site, e.g. /blog
url: "periodbox.de" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
show_downloads: true
github:
  zip_url: http://periodbox.de/assets/flyer.pdf
  tar_url:  http://periodbox.de/assets/flyer.zip

# Build settings
theme: jekyll-theme-cayman
plugins:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
